### ISSUE TITLE
type error on line 129

### ISSUE THREAD

**Issue by ceraz68** [codyc1515/homebridge-sma-inverter#6] opened 2019-11-03 11:19 UTC
Hello, I have a error on line 129.

I entered the IP address in the settings windows. Editing index.js and replacing the client.connectTCP(addresses[0]) by client.connectTCP("192.168.0.3", { port: 502 }) worked for me.

**Comment by codyc1515** [comment] 2019-11-03 11:20
Could you please provide the error so that I could look into the root cause for this?

**Comment by ceraz68** [comment] 2019-11-03 11:20
Yes I was just about to paste it:

TypeError: Cannot read property '0' of undefined
    at SMAInverter.<anonymous> (/homebridge/node_modules/homebridge-sma-inverter/index.js:129:40)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:196:10)

**Comment by rangerek** [comment] 2019-11-07 15:40
> Hello, I have a error on line 129.
> 
> I entered the IP address in the settings windows. Editing index.js and replacing the client.connectTCP(addresses[0]) by client.connectTCP("192.168.0.3", { port: 502 }) worked for me.

worked for me as well (issue #7)

**Comment by rangerek** [comment] 2019-11-21 10:33
just reminding that in 2.1.0 issue persists and requires manual change in line 130 this time :(

**Comment by codyc1515** [comment] 2020-05-19 07:26
Hopefully the IP address issue should be fixed now in https://github.com/codyc1515/homebridge-sma-inverter/commit/94d1c2cd2b33ccf5b3542ac57defab978135c1c9. Can you let me know?

**Comment by rangerek** [comment] 2020-05-22 13:47
I can confirm that after update it works :) you can close it

**Comment by codyc1515** [comment] 2020-11-30 06:29
Fixed by adding DNS _and_ IP address support.

**Closed as completed by codyc1515** 2020-11-30 06:29 UTC
Labels: bug
