### ISSUE TITLE
Refresh interval is in minutes = 60.000 milliseconds 

### ISSUE THREAD

**Issue by drheck** [codyc1515/homebridge-sma-inverter#27] opened 2021-03-13 15:31 UTC
Hi,
i have copied last year in August this plugin and modified it for my special purposes (i have 2 inverters and i wants the sum of the values).

Today i get the update, so i made a diff with version 3.2.0 with the 2.2.2 and my modification in order to get the mods you made.

So i see the change from
2.2.2: 	    this.refreshInterval = (config['refreshInterval'] * 60000) || 60000;
TO newest:  this.refreshInterval = (config['refreshInterval'] * 1000) || 60000;	
If you want this, so please change (minutes) to (seconds) or change it back to 60.000.
I think a refresh lower than a minute is not parcticable.

regards,
Peter

**Comment by codyc1515** [comment] 2021-04-02 04:19
Refresh lower than a minute works fine, but it seems like the inverter locks up sometimes and becomes unresponsive to any commands or even the web interface. I haven't been able to determine the root cause but it's likely due to this plugin.

**Comment by drheck** [comment] 2021-04-02 08:26
Hi,
i think there is an error with the dimension of the refreshInterval!
I want install your update, but i get the error in attached screenshot and logfile.
Peter
![errorupdate](https://user-images.githubusercontent.com/49845838/113396802-6692a580-939c-11eb-8d22-67551718ae4a.PNG)
[2021-04-02T08_13_59_532Z-debug.log](https://github.com/codyc1515/homebridge-sma-inverter/files/6248537/2021-04-02T08_13_59_532Z-debug.log)

**Comment by mitch7391** [comment] 2022-02-09 03:19
@drheck is this still an issue?

**Comment by drheck** [comment] 2022-02-10 13:26
You can close it. I do not use the plugin anymore.

**Comment by mitch7391** [comment] 2022-02-10 13:34
I cannot myself, I am just trying to help @codyc1515 with a bit of tidy up here and there. Yourself or him will have to close this out.

**Comment by wimleers** [comment] 2022-09-18 21:43
This definitely is still an issue. The refresh interval is _not_ in minutes, but in seconds.

I had it configured to `1`, which resulted in an update every second! My inverter did not crash in the weeks it ran at this rate though. I changed it to `30`, now it updates twice a minute, which is plenty.

**Closed as completed** 2022-11-08 07:40 UTC
Labels: question, wontfix
